# Application name
name: deploy-container-app

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "main"
    paths:
      - "apps/container/**"

defaults:
  run:
    shell: bash
    working-directory: apps/container

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install app dependencies
        run: npm i

      - name: build app
        run: npm run build

      - uses: chrislennon/action-aws-cli@v2
      # All commands after this point have access to the AWS CLI
      - run: aws s3 sync dist s3://${{secrets.AWS_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
